name: Build Releases

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual trigger from the GitHub Actions tab

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            zip_suffix: linux
          - os: windows-latest
            zip_suffix: win32
          - os: macos-13
            zip_suffix: darwin
          - os: macos-14
            zip_suffix: darwin_arm64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Executable
        run: pyinstaller --name ScriptCutter --windowed --onedir main.py --exclude-module PySide6.QtWebEngineCore --exclude-module PySide6.QtWebEngineWidgets --exclude-module PySide6.QtNetwork --exclude-module PySide6.QtSql --exclude-module PySide6.QtQml --exclude-module PySide6.QtQuick --exclude-module PySide6.Qt3DCore --exclude-module PySide6.QtSensors --exclude-module PySide6.QtSerialPort --exclude-module PySide6.QtBluetooth --exclude-module tkinter --exclude-module unittest --exclude-module pydoc
        shell: bash

      - name: Package Windows and Linux
        if: runner.os != 'macOS'
        run: |
          cd dist
          python -m zipfile -c ../ScriptCutter-${{ matrix.os }}.zip ScriptCutter
        shell: bash

      - name: Package macOS
        if: runner.os == 'macOS'
        run: |
          cd dist
          python -m zipfile -c ../ScriptCutter-${{ matrix.os }}.zip ScriptCutter.app
        shell: bash

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ScriptCutter-${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
